apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Release.Name }}-apache
spec:
  type: {{ .Values.apache.service.type }}
  ports:
    - port: {{ .Values.apache.service.port }}
      targetPort: {{ .Values.apache.container.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-apache 