apiVersion: v1
kind: Service
metadata:
  name: {{ include "multiple-deployment.fullname" . }}-nginx
  labels:
    {{- include "multiple-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.container.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-nginx 